### ISSUE TITLE
Better to support Unicode scripts rather than blocks in `\p` and `\P`

### ISSUE THREAD

**Issue by jclark** [ietf-wg-jsonpath/iregexp#10]
I think it is better to support script names than block names for `\p` and `\P`.

Unicode block names are not supported by regexp implementations an interoperable way.  Block names as specified in

https://www.unicode.org/Public/UNIDATA/Blocks.txt

allow ASCII alpha-numerics, hyphens and spec.  Unicode says these names are supposed to be matched using

http://www.unicode.org/reports/tr44/#UAX44-LM3

(which says to ignore case, whitespace, underscore, hyphens, and any initial prefix string "is"). But implementations don't do this and compare names using a wide variety of different rules (as partially described by "Unicode blocks" section of https://www.regular-expressions.info/unicode.html).

Usage of block names can easily be replaced by ranges.  Furthermore, block names are not covered by the Unicode stability policy.

Scripts names don't have such a wide range of characters (there are also 4-char short script names) and scripts are generally preferable to blocks for regexps as explained here:

https://unicode.org/reports/tr18/#Character_Blocks

Script is in the minimal list of properties that Unicode requires but block is not

http://unicode.org/reports/tr18/#RL1.2

**Comment by cabo** [comment]
Thank you!  Very useful input.
We are having an interim meeting (per web conference) of the JSONPath WG at this very moment; I'll look at this later today.

**Comment by jclark** [comment]
I just looked again at XSD and see that sadly it doesn't support scripts in `\p`.  Every major regex implementation that I am aware of that does Unicode and `\p` does support scripts (Go, PCRE, Java, C#, Ruby).  So if XSD compatibility is crucial (not sure why it would be at this point), my suggestion would be just to get rid of blocks.

One could argue that supporting only the general category in `\p` is consistent with not supporting character set intersection/difference: once you have multiple things (e.g. script and category), you really need to be able to have intersections/differences of them.
