### ISSUE TITLE
Escape sequences singleCharEsc

### ISSUE THREAD

**Issue by springcomp** [ietf-wg-jsonpath/iregexp#18]
The various expressions referred to at the end of the document make for a reasonably complete compliance test suite.

I'm creating a [quick checker](https://github.com/springcomp/iregexp/blob/main/src/Checker.ts) that I think could be useful to this project as I will need to embed and process Regex expressions in one of my projects.

That said, I fail to see how: ` \S ` and ` \d ` validate with the BNF. The way I read the spec is that a very small subset of characters support escaping.

Can you please clarify what I am missing ?

**Comment by cabo** [comment]
The introduction for the Appendix says "With the exception of some (often surprisingly dubious) usage of multi-character escapes".  You found those exceptions.  Please see Table 1 for how to handle them.

Thank you for your input!
