### ISSUE TITLE
rfc6021.txt  938

### ISSUE THREAD

**Issue by springcomp** [ietf-wg-jsonpath/iregexp#19]
It seems to me the following expression is invalid:

``  (([^:]+:){6}(([^:]+:[^:]+)|(.*\..*)))| ``

As it ends with a dangling `|` without a completed branch?
Is my analysis correct?

**Comment by cabo** [comment]
In YANG, you need to reconstruct the the regex from the whole pattern:

```
 pattern '(([^:]+:){6}(([^:]+:[^:]+)|(.*\..*)))|'
             + '((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?)'
             + '(%.+)?';
```

(the plus signs outside the strings mean concatenation).

My simple extractor program for Appendix A didn't do this (which also helped with keeping the regexes with the 69-character limit of RFCs, which was relevant before we decided to make this a "to be removed in RFC" section).

But note that the grammar says:

```
i-regexp = branch *( "|" branch )
branch = *piece
```

So a branch with zero pieces is valid.

If you are aware of a situation where this would lead to interoperability problems, we would like to hear!

**Comment by springcomp** [comment]
> So a branch with zero pieces is valid.

Thank you. That's where I mistakenly read _one or more_ instead. Thank you for the clarification.
