### ISSUE TITLE
Please, can you give an example of a mapping to ECMAScript

### ISSUE THREAD

**Issue by springcomp** [ietf-wg-jsonpath/iregexp#20]
I have difficult time to understand this paragraph from the draft:

> For any dots (`.`) outside character classes (first alternative of `charClass` production): replace dot by `[^\n\r]`.

I assume this means:

- replace `.` in `` .* `` to `` [^\n\r]* ``
- do not replace `.` in `` [a-z.] `` (as it is in a character class)
- do not replace `.` in `` \. `` (obviously as it is escaped)

Is my understanding correct?

**Comment by cabo** [comment]
Your understanding is correct, and I take this as input that "dots" needs to be replaced with "unescaped dots" in this sentence.
